language: node_js
node_js:
- "node"
    
deploy:
    # deploy to all environments
  - provider: script
    script: bash scripts/build.sh $TRAVIS_COMMIT
    on:
      branch: master

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t innablr-test .
      - docker images
      - docker tag innablr-test $DOCKER_USERNAME/innablr-test
      - docker push $DOCKER_USERNAME/innablr-test
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/innablr-test cat status.json
    - script: docker run --rm $DOCKER_USERNAME/innablr-test cat status.json

notifications:
  email:
    recipients:
    - rchowson@yahoo.com
    on_success: change
    on_failure: always
