language: node_js
node_js:
- "node"

env:
  MY_STAGE=test VERSION=1.0
  MY_STAGE=build VERSION=1.0
  MY_STAGE=publish VERSION=1.0
    
deploy:
    # deploy to all environments
  - provider: script
    script: bash scripts/build.sh $TRAVIS_COMMIT
    on:
      branch: master

script:

notifications:
  email:
    recipients:
    - rchowson@yahoo.com
    on_success: change
    on_failure: always