language: node_js
node_js:
- "node"
    
deploy:
    # deploy to all environments
  - provider: script
    script: bash scripts/build.sh $TRAVIS_COMMIT
    on:
      branch: master

jobs:
  include:
    - stage: test
      script:
        - echo "Running scripts for test env"
    - stage: build
      script:
        - echo "Running scripts for build env"
    - stage: publish
      script:
        - echo "Running scripts for publish env"
        
notifications:
  email:
    recipients:
    - rchowson@yahoo.com
    on_success: change
    on_failure: always
